.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH ecd-check 1  "check " 
.SH NAME
ecd\-check \- Detect file encoding(s)
.SH SYNOPSIS
\fBecd check\fR [\fB\-\-color\fR] [\fB\-f\fR|\fB\-\-file\fR] [\fB\-d\fR|\fB\-\-dir\fR] [\fB\-r\fR|\fB\-\-recursive\fR] [\fB\-p\fR|\fB\-\-pattern\fR] [\fB\-i\fR|\fB\-\-ignore\fR] [\fB\-e\fR|\fB\-\-exclude\fR] [\fB\-\-no\-default\-excludes\fR] [\fB\-j\fR|\fB\-\-jobs\fR] [\fB\-v\fR|\fB\-\-verbose\fR] [\fB\-q\fR|\fB\-\-quiet\fR] [\fB\-h\fR|\fB\-\-help\fR] 
.SH DESCRIPTION
Detect file encoding(s)
.SH OPTIONS
.TP
\fB\-\-color\fR \fI<WHEN>\fR [default: never]
When to colorize encoding labels (`[UTF\-8]`, `[SKIP]`, …) in batch output
.br

.br
\fIPossible values:\fR
.RS 14
.IP \(bu 2
auto: Colorize when stdout is a terminal and `NO_COLOR` is unset
.IP \(bu 2
never: Never colorize (default)
.IP \(bu 2
always: Always colorize (ANSI escapes; useful for piping to `less \-R`)
.RE
.TP
\fB\-f\fR, \fB\-\-file\fR \fI<PATH>\fR
File(s) to check (repeatable)
.TP
\fB\-d\fR, \fB\-\-dir\fR \fI<PATH>\fR
Directory/directories to scan (repeatable); defaults to `.` when `\-r` or `\-p` is given alone
.TP
\fB\-r\fR, \fB\-\-recursive\fR
Recursively scan into subdirectories (used with `\-d`, or current directory when `\-d` is omitted)
.TP
\fB\-p\fR, \fB\-\-pattern\fR \fI<GLOB>\fR
Glob pattern to filter files (`*.java`; with `\-r` matches at any depth)
.TP
\fB\-i\fR, \fB\-\-ignore\fR \fI<ENC>\fR
Ignore files with this encoding (case\-insensitive)
.br

.br
\fIPossible values:\fR
.RS 14
.IP \(bu 2
utf\-8
.IP \(bu 2
utf\-16le
.IP \(bu 2
utf\-16be
.IP \(bu 2
gbk
.IP \(bu 2
big5
.IP \(bu 2
shift_jis
.IP \(bu 2
euc\-jp
.IP \(bu 2
euc\-kr
.IP \(bu 2
iso\-2022\-jp
.IP \(bu 2
koi8\-r
.IP \(bu 2
koi8\-u
.IP \(bu 2
windows\-1251
.IP \(bu 2
x\-mac\-cyrillic
.IP \(bu 2
iso\-8859\-2
.IP \(bu 2
iso\-8859\-3
.IP \(bu 2
iso\-8859\-4
.IP \(bu 2
iso\-8859\-5
.IP \(bu 2
iso\-8859\-6
.IP \(bu 2
iso\-8859\-7
.IP \(bu 2
iso\-8859\-8
.IP \(bu 2
iso\-8859\-8\-i
.IP \(bu 2
iso\-8859\-10
.IP \(bu 2
iso\-8859\-13
.IP \(bu 2
iso\-8859\-14
.IP \(bu 2
iso\-8859\-15
.IP \(bu 2
iso\-8859\-16
.IP \(bu 2
windows\-1250
.IP \(bu 2
windows\-1252
.IP \(bu 2
windows\-1253
.IP \(bu 2
windows\-1254
.IP \(bu 2
windows\-1255
.IP \(bu 2
windows\-1256
.IP \(bu 2
windows\-1257
.IP \(bu 2
windows\-1258
.IP \(bu 2
ibm866
.IP \(bu 2
windows\-874
.IP \(bu 2
macintosh
.IP \(bu 2
ascii
.RE
.TP
\fB\-e\fR, \fB\-\-exclude\fR \fI<NAME>\fR
Additional directory names to exclude
.TP
\fB\-\-no\-default\-excludes\fR
Disable default directory excludes (.git, node_modules, target)
.TP
\fB\-j\fR, \fB\-\-jobs\fR \fI<N>\fR
Number of parallel jobs
.TP
\fB\-v\fR, \fB\-\-verbose\fR
Print statistics to stderr
.TP
\fB\-q\fR, \fB\-\-quiet\fR
Suppress normal output (errors only)
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help (see a summary with \*(Aq\-h\*(Aq)
